Repository ArnauMiro/pyLowOrder, pull requests merged in 2025-03, with the labels that each got.

#125 Ensight deprecation
  pyLOM/inp_out/__init__.py
  pyLOM/inp_out/io_ensight.py
  pyLOM/inp_out/io_ensight.pyx
  pyLOM/inp_out/io_paraview.py
  setup.py
Labels: enhancement

#126 123 ensure that the vtkhdf format properly uses the append and write modes
  .gitignore
  Examples/GPOD/example_GPOD.py
  Examples/GPOD/example_GPOD_vector.py
  Examples/example_regression.py
  Examples/example_stats.py
  Makefile
  Testsuite/references/GPOD_Cylinder.ref
  Testsuite/references/GPOD_Cylinder1.ref
  Testsuite/run_testsuite.py
  Testsuite/runs/tsuite_GPOD.py
  Testsuite/runs/tsuite_GPOD_vector.py
  Testsuite/testsuite.json
  pyLOM/DMD/wrapper.py
  pyLOM/DMD/wrapper.pyx
  pyLOM/GPOD/__init__.py
  pyLOM/GPOD/utils.py
  pyLOM/GPOD/wrapper.py
  pyLOM/POD/wrapper.py
  pyLOM/POD/wrapper.pyx
  pyLOM/SPOD/wrapper.py
  pyLOM/SPOD/wrapper.pyx
  pyLOM/__init__.py
  pyLOM/inp_out/io_paraview.py
  pyLOM/inp_out/io_vtkh5.py
  pyLOM/vmmath/__init__.py
  pyLOM/vmmath/averaging.py
  pyLOM/vmmath/averaging.pyx
  pyLOM/vmmath/cfuncs.pxd
  pyLOM/vmmath/cfuncs.pyx
  pyLOM/vmmath/fft.py
  pyLOM/vmmath/fft.pyx
  pyLOM/vmmath/geometric.py
  pyLOM/vmmath/geometric.pyx
  pyLOM/vmmath/maths.py
  pyLOM/vmmath/maths.pyx
  pyLOM/vmmath/regression.py
  pyLOM/vmmath/regression.pyx
  pyLOM/vmmath/src/fft.c
  pyLOM/vmmath/src/fft.h
  pyLOM/vmmath/src/geometric.c
  pyLOM/vmmath/src/geometric.h
  pyLOM/vmmath/src/regression.c
  pyLOM/vmmath/src/regression.h
  pyLOM/vmmath/src/stats.c
  pyLOM/vmmath/src/stats.h
  pyLOM/vmmath/src/truncation.c
  pyLOM/vmmath/src/truncation.h
  pyLOM/vmmath/src/vector_matrix.c
  pyLOM/vmmath/src/vector_matrix.h
  pyLOM/vmmath/stats.py
  pyLOM/vmmath/stats.pyx
  pyLOM/vmmath/svd.py
  pyLOM/vmmath/svd.pyx
  pyLOM/vmmath/truncation.py
  pyLOM/vmmath/truncation.pyx
  pyLOM/vmmath/wrapper.py
  pyLOM/vmmath/wrapper.pyx
  requirements.txt
  requirements_optional.txt
  setup.py
Labels: bug

#127 Add Docs
  .github/workflows/deploy_documentation.yml
  .gitignore
  docs/README_docs.md
  docs/source/Makefile
  docs/source/_static/custom.css
  docs/source/_static/index-images/api.svg
  docs/source/_static/index-images/contributor.svg
  docs/source/_static/index-images/getting_started.svg
  docs/source/_static/index-images/install.svg
  docs/source/_templates/module.rst_t
  docs/source/_templates/package.rst_t
  docs/source/_templates/toc.rst_t
  docs/source/api/modules.rst
  docs/source/api/pyLOM.DMD.rst
  docs/source/api/pyLOM.GPR.rst
  docs/source/api/pyLOM.MANIFOLD.rst
  docs/source/api/pyLOM.NN.architectures.rst
  docs/source/api/pyLOM.NN.rst
  docs/source/api/pyLOM.POD.rst
  docs/source/api/pyLOM.SPOD.rst
  docs/source/api/pyLOM.inp_out.rst
  docs/source/api/pyLOM.rst
  docs/source/api/pyLOM.utils.rst
  docs/source/api/pyLOM.vmmath.rst
  docs/source/conf.py
  docs/source/examples.rst
  docs/source/index.rst
  docs/source/make.bat
  docs/source/notebook_examples/burgers_PINN_training_pipeline.ipynb
  pyLOM/NN/architectures/autoencoders.py
  pyLOM/NN/architectures/encoders_decoders.py
  pyLOM/NN/architectures/kan.py
  pyLOM/NN/architectures/mlp.py
  pyLOM/NN/callbacks.py
  pyLOM/NN/stats.py
  pyLOM/NN/utils.py
  requirements_docs.txt
Labels: enhancement

#128 fixed error on deploy_documentation.yml
  .github/workflows/deploy_documentation.yml
Labels: bug

#138 Allow the compilation of separate modules
  Makefile
  options.cfg
  pyLOM/vmmath/averaging.py
  pyLOM/vmmath/averaging.pyx
  pyLOM/vmmath/fft.py
  pyLOM/vmmath/fft.pyx
  pyLOM/vmmath/geometric.py
  pyLOM/vmmath/geometric.pyx
  pyLOM/vmmath/maths.py
  pyLOM/vmmath/maths.pyx
  setup.py
Labels: enhancement

#143 Fix dynamic versioning
  pyLOM/__init__.py
  pyproject.toml
  setup.py
Labels: documentation, enhancement

#145 Fixing #144
  pyLOM/inp_out/io_h5.py
Labels: bug

#148 Fix deprecation and updated setuptools
  pyproject.toml
  requirements.txt
Labels: bug

#152 149 update docs
  docs/source/_ext/module_alias.py
  docs/source/api/pyLOM.io.rst
  docs/source/api/pyLOM.math.rst
  docs/source/api/pyLOM.rst
  docs/source/conf.py
  docs/source/installation/installation_pypi.rst
  docs/source/notebook_examples/NN/KAN_training.ipynb
Labels: documentation

#157 Fix ndime
  pyLOM/partition_table.py
Labels: bug

#159 158 bugfix docs
  Examples/example_dataset.py
  docs/source/conf.py
  docs/source/notebook_examples/example_POD_cylinder.ipynb
Labels: bug, documentation

#161 updated version of gh-pages deploy action
  .github/workflows/deploy_documentation.yml
  docs/source/notebook_examples/example_POD_cylinder.ipynb
Labels: bug, documentation
